trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Zip code and move to s3
  steps:
    - task: S3Upload@1
      inputs:
        awsCredentials: 'logixos-task1-connection'
        regionName: 'us-east-1'
        bucketName: 'logixos-task'
        globExpressions: '**'
        targetFolder: 'task2'
        filesAcl: 'public-read'

- job: Deploy Lambda Function
  steps:
    - task: LambdaDeployFunction@1
      inputs:
        awsCredentials: 'logixos-task1-connection'
        regionName: 'us-east-1'
        deploymentMode: 'codeandconfiguration'
        functionName: 'logixos-task2'
        functionHandler: 'lambda_handler'
        runtime: 'python3.8'
        codeLocation: 'localfile'
        logRequest: true
        logResponse: true
        roleARN: 'arn:aws:iam::355385224066:role/logixos-role'